version: '3.9'

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run start:dev
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/nokoroa_db
      - FRONTEND_URL=http://localhost:3000
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - NODE_ENV=development
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nokoroa_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  node_modules:
